### ISSUE TITLE
Floorplan is not loaded in HA 0.106.0

### ISSUE THREAD

**Issue by tlpbu** [pkozul/lovelace-floorplan#20]
Floorplan card content is not loaded anymore after upgrade to Home Assistant 0.106.0.

Found following  in the logs:
`2/26/2020, 9:49:34 PM ERROR TypeError: Cannot add property svg, object is not extensible
    at http://192.168.0.2:8123/local/floorplan/lib/floorplan.js?v=1.1.14:90:27`

**Comment by d4v3d** [comment]
Floorplan is not working in Lovelace for me either after upgrading to 106.0 but the error I am seeing is different than above. It is: 
ERROR initSinglePage/<@https://x.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:90:11

**Comment by d4v3d** [comment]
Update: I reverted to 105.5 and Floorplan is working again.

**Comment by ruslangreen** [comment]
HASSIO 0.106.0 floorplan error
27.02.2020, 10:05:17 ERROR TypeError: Cannot add property svg, object is not extensible
at https://XXX/local/floorplan/lib/floorplan.js?v=1.1.8:90:27

**Comment by KKnishev** [comment]
> Cannot add property svg, object is not extensible
> at https://XXX/local/floorplan/lib/floorplan.js?v=1.1.8:90:27

The same :/

**Comment by nathanfiscus** [comment]
Floorplan modifies the config object from Lovelace directly by appending the svg.  This object is now frozen in HA 0.106 per https://developers.home-assistant.io/blog/2020/02/18/106-custom-card-changes/ and now throws an error when an attempt to modify it is made. 

PR #22 patches floorplan.js by creating a copy of the config object.

Line 61 of floorplan.js
`this.config = Object.assign({},config);`

**Comment by KKnishev** [comment]
> Line 61 of floorplan.js
> `this.config = Object.assign({},config);`

not working for me, the same on 0.106.1:
object is not extensible at https://XXX/local/floorplan/lib/floorplan.js?v=1.1.8:90:27

**Comment by ruslangreen** [comment]
> not working for me to, the same on 0.106.1:


> > Line 61 of floorplan.js
> > `this.config = Object.assign({},config);`
> 
> not working for me, the same on 0.106.1:
> object is not extensible at https://XXX/local/floorplan/lib/floorplan.js?v=1.1.8:90:27

**Comment by ruslangreen** [comment]
My log
28.02.2020, 10:29:24 ERROR TypeError: Cannot add property entities, object is not extensible
    at Floorplan.initGetEntityRuleEntities (https://xxx/local/floorplan/lib/floorplan.js?v=1.1.8:671:23)
    at Floorplan.initEntityRule (https://xxx/local/floorplan/lib/floorplan.js?v=1.1.8:600:29)
    at Floorplan.initRules (https://xxx/local/floorplan/lib/floorplan.js?v=1.1.8:591:16)
    at Floorplan.initFloorplan (https://xxx/local/floorplan/lib/floorplan.js?v=1.1.8:564:12)
    at https://xxx/local/floorplan/lib/floorplan.js?v=1.1.8:93:27

**Comment by bstrakt** [comment]
> Floorplan modifies the config object from Lovelace directly by appending the svg. This object is now frozen in HA 0.106 per https://developers.home-assistant.io/blog/2020/02/18/106-custom-card-changes/ and now throws an error when an attempt to modify it is made.
> 
> PR #22 patches floorplan.js by creating a copy of the config object.
> 
> Line 61 of floorplan.js
> `this.config = Object.assign({},config);`

Thank you, this worked for me. After making the modification in floorplan.js, I had also increased the version of floorplan-card.js in ui-lovelace (for example from 1.1.14 to 1.1.15) and refresh the browser.

  - url: /local/floorplan/floorplan-card.js?v=1.1.15
    type: module

**Comment by Luc3as** [comment]
Hi guys, the above fix worked fine, I just want to add, if you are using, Custom-compact-header there could be another problem when the floorplan is not loading. I am going to update this component and try if it works.

**Comment by KKnishev** [comment]
> Line 61 of floorplan.js
> this.config = Object.assign({},config);
> increased the version of floorplan-card.js to 1.1.15
ha core restart
clear the browser cache
not working form me also :(

ERROR TypeError: Cannot add property svg, object is not extensible
at https://XXX/local/floorplan/lib/floorplan.js?v=1.1.8:90:27

**Comment by Luc3as** [comment]
I had to edit line 17 in floorplan-card.js
to this 
this.config = Object.assign({}, config);

**Comment by KKnishev** [comment]
> I had to edit line 17 in floorplan-card.js

nothing new, not working

**Comment by bstrakt** [comment]
> > I had to edit line 17 in floorplan-card.js
> 
> nothing new, not working

You can try to increase the version on the card config in ui-lovelace:

    cards:
      - type: custom:floorplan-card
        config:
          image: /local/floorplan/floorplan.svg?v=1.1.20
          stylesheet: /local/floorplan/floorplan.css?v=1.1.15

**Comment by KKnishev** [comment]
Already tried this:
```
  - title: FLOORPLAN
    icon: mdi:floor-plan
    panel: true
    cards:
      - config:
          image: /local/floorplan/dd103.svg?v=1.1.20
          log_level: error
          debug: true
          stylesheet: /local/floorplan/dd103.css?v=1.1.15
        type: 'custom:floorplan-card'
```

**Comment by nathanfiscus** [comment]
You will need to clear the cache.  The file that is causing the issue is referenced from the card, not in your Lovelace config.

**Comment by jacekpaszkowski** [comment]
I caught this error in debugger when loading card

line: 690
```js
      // HA entity treated as is
      if (rule.entity) {
        rule.entities = [rule.entity];
      }
```

```
TypeError: Cannot assign to read only property 'entities' of object '#<Object>'
```

**Comment by nathanfiscus** [comment]
Try replacing the patch with `this.config = JSON.parse(JSON.stringify(config));` instead.

**Comment by jacekpaszkowski** [comment]
> Try replacing the patch with `this.config = JSON.parse(JSON.stringify(config));` instead. Also can you confirm the Browser you are using and the version of Floorplan you are using?

This worked for me! I use Chrome v79.0.3945.130

**Comment by nathanfiscus** [comment]
Okay, that means some configs are modifying the the properties that are also frozen.  I will adjust the patch with a more efficient way of performing a deep copy on the config.

**Comment by bartplessers** [comment]
same over here.
I got an error
`ERROR TypeError: cannot assign to read only poperty 'svg' of object '#' at https://.../local/floorplan/lib/floorplan.js?v=1.1.8:90:27`

Fixed with modification of` homeassistant/www/floorplan/floorplan-card.js`, line 17
`
    this.config = JSON.parse(JSON.stringify(config));
`

and my lovelace config

resources:
```
  - type: module
    url: /local/floorplan/floorplan-card.js?v=1.1.15
  - badges: []
    cards:
      - config:
          image: /local/floorplan/plans/sara/grondplan.svg?v=1.1.15
          log_level: error
          rules: []
          stylesheet: /local/floorplan/plans/sara/grondplan.css?v=1.1.15
          svg: {}
        title: Ho(te)lletje Scarabee
        type: 'custom:floorplan-card'
    icon: 'mdi:floor-plan'
    panel: true
    path: floorplan
    title: FLOORPLAN
```

(I increased the version from `v=1.1.14` to `v=1.1.15`, this helped me on mobile devices to clear the local cache)

**Comment by vgonzalez84** [comment]
> My log
> 28.02.2020, 10:29:24 ERROR TypeError: Cannot add property entities, object is not extensible
> at Floorplan.initGetEntityRuleEntities (https://xxx/local/floorplan/lib/floorplan.js?v=1.1.8:671:23)
> at Floorplan.initEntityRule (https://xxx/local/floorplan/lib/floorplan.js?v=1.1.8:600:29)
> at Floorplan.initRules (https://xxx/local/floorplan/lib/floorplan.js?v=1.1.8:591:16)
> at Floorplan.initFloorplan (https://xxx/local/floorplan/lib/floorplan.js?v=1.1.8:564:12)
> at https://xxx/local/floorplan/lib/floorplan.js?v=1.1.8:93:27

I have the same problem:
ERROR TypeError: Cannot add property entities, object is not extensible
    at Floorplan.initGetEntityRuleEntities (https://vicgone84.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:671:23)
    at Floorplan.initEntityRule (https://vicgone84.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:600:29)
    at Floorplan.initRules (https://vicgone84.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:591:16)
    at Floorplan.initFloorplan (https://vicgone84.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:564:12)
    at https://vicgone84.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:93:27

**Comment by bbaixo** [comment]
Hi,

I have the same issue of _vgonzalez84_

The floorplan isn't load.

**Comment by nathanfiscus** [comment]
@vgonzalez84 and @bbaixo  Can you change line 16 or 17 to 
`this.config = JSON.parse(JSON.stringify(config));` 
This seems to be working for everyone that is getting an error around Floorplan.initGetEntityRuleEntities call.

**Comment by bbaixo** [comment]
Hi @nathanfiscus,

Still not working.

My setup:
- Home Assistant 0.106.2
- browser (Chrome and Edge)
- I install today Floorplan

Error: 
"3/2/2020, 6:06:36 PM ERROR TypeError: rule.entities.filter is not a function
    at Floorplan.initGetEntityRuleEntities (https://xxxxx.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:676:41)
    at Floorplan.initEntityRule (https://xxxxx.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:600:29)
    at Floorplan.initRules (https://xxxxx.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:591:16)
    at Floorplan.initFloorplan (https://xxxxx.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:564:12)
    at https://xxxxx.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:93:27"

thanks

**Comment by nathanfiscus** [comment]
@bbaixo that is a different error that the one related to this issue.  I would verify that your yaml configuration for floorplan is valid.

**Comment by bbaixo** [comment]
@nathanfiscus 

It's working, I miss a dash in the code.

Thanks for your time and help.

Best regards,

**Comment by ruslangreen** [comment]
floorplan.js
Line 61 of floorplan.js
this.config = Object.assign({},config);

+
floorplan-card.js
Can you change line 16 or 17 to
this.config = JSON.parse(JSON.stringify(config));

+ clear app & browser cach 

===

It's working!

**Comment by kwdavidson** [comment]
Both of these changes have been applied and are in `master`.

**Comment by d4v3d** [comment]
Hi all,

Thanks for the work on this!! 

I have made both the changes to the js files but am still seeing an initGetEntityRuleEntities error. Is this potentially related?

```
3/12/2020, 11:19:41 AM ERROR initGetEntityRuleEntities@https://x.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:671:26
initEntityRule@https://x.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:600:29
initRules@https://x.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:591:16
initFloorplan@https://x.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:564:12
initSinglePage/</<@https://x.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:93:27
floorplan.js:1681:21
    log https://x.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:1681
    handleError https://x.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:1656
    init https://x.duckdns.org/local/floorplan/lib/floorplan.js?v=1.1.8:71
```

**Comment by lklinggaard** [comment]
Don't know if this is related, but after upgrading to the last release I get this error in the Chrome consol.

`Uncaught (in promise) TypeError: Class constructor $ cannot be invoked without 'new'
    at Floorplan.log (VM1927 floorplan.js:1702)
    at Floorplan.handleError (VM1927 floorplan.js:1656)
    at VM1927 floorplan.js:71`

Any thoughts?

**Comment by exetico** [comment]
Hi all,

We've just pushed the first official version - check the [release overview](https://github.com/pkozul/lovelace-floorplan/releases). I think this is fixed, too :-)
